Vagrant.configure("2") do |config|
  config.vm.define "web" do |web|
    web.vm.box = "centos/7"
    web.vm.box_check_update = false
    web.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--cpus", "1"]
      v.customize ["modifyvm", :id, "--memory", "512"]
      v.customize ["modifyvm", :id, "--name", "web"]
    end
    web.vm.network :private_network, ip: "10.10.0.30"
    web.ssh.insert_key = false
    web.vm.boot_timeout = 800
    web.ssh.private_key_path = ["~/.ssh/id_rsa", "~/.vagrant.d/insecure_private_key"]
    web.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
    web.vm.hostname = "web"
  end

  config.vm.define "db" do |db|
    db.vm.box = "centos/7"
    db.vm.box_check_update = false
    db.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--cpus", "1"]
      v.customize ["modifyvm", :id, "--memory", "512"]
      v.customize ["modifyvm", :id, "--name", "db"]
    end
    db.vm.network :private_network, ip: "10.10.0.20"
    db.ssh.insert_key = false
    db.vm.boot_timeout = 800
    db.ssh.private_key_path = ["~/.ssh/id_rsa", "~/.vagrant.d/insecure_private_key"]
    db.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
    db.vm.hostname = "db"
  end

  config.vm.define "bastion" do |bastion|
    bastion.vm.box = "centos/7"
    bastion.vm.box_check_update = false
    bastion.vm.provider :virtualbox do |v|

      v.customize ["modifyvm", :id, "--cpus", "1"]
      v.customize ["modifyvm", :id, "--memory", "512"]
      v.customize ["modifyvm", :id, "--name", "bastion"]
    end
    bastion.vm.network :private_network, ip: "10.10.0.10"
    bastion.vm.network "public_network", bridge: "wlo1", use_dhcp_assigned_default_route: true
    bastion.vm.hostname = "bastion"
    bastion.ssh.insert_key = false
    bastion.vm.boot_timeout = 800
    bastion.ssh.private_key_path = ["~/.ssh/id_rsa", "~/.vagrant.d/insecure_private_key"]
    bastion.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
    bastion.vm.provision "shell", inline: "sudo sysctl -w net.ipv4.ip_forward=1"
  end
end
