---
# tasks file for nginx_role
- name: Add nginx yum repository
  yum_repository:
    name: nginx
    description: Nginx Repository
    baseurl: http://nginx.org/packages/centos/7/$basearch/
    gpgkey: https://nginx.org/keys/nginx_signing.key
    gpgcheck: yes
    enabled: yes
  when: ansible_os_family == "RedHat"

- name: Add epel repository
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
    gpgkey: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7
    gpgcheck: yes
    enabled: yes
  when: ansible_os_family == "RedHat"

- name: ensure a list of packages installed
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - nginx
    - epel-release
    - yum-utils
    - certbot 
    - python2-certbot-nginx
  when: ansible_os_family == "RedHat"
  
  notify:
    - nginx_enable
  
- name: Install nginx apt
  apt:
    name: nginx
    state: latest
  when: ansible_os_family == "Debian"
  notify:
    - nginx_enable
